# Generated by Django 3.1.3 on 2020-12-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(choices=[('ROUND 1', 'R1'), ('ROUND 2', 'R2'), ('ROUND 3', 'R3'), ('ROUND 4', 'R4'), ('ROUND 5', 'R5')], max_length=8)),
                ('player1score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('player2score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team')),
            ],
        ),
    ]
