# Generated by Django 3.1.3 on 2020-12-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20201217_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='round_no',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='player1',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(choices=[('R1', 'Round 1'), ('R2', 'Round 2'), ('R3', 'Round 3'), ('R4', 'Round 4'), ('R5', 'Round 5')], max_length=2)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.score')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team')),
            ],
        ),
    ]
