# Generated by Django 3.1.3 on 2020-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20201218_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player1score',
            field=models.CharField(choices=[('Round 1', (('5', 'A'), ('4', 'B'), ('3', 'C'), ('2', 'D'), ('1', 'E'), ('0', 'F'))), ('Round 2', (('6', 'A'), ('5', 'B'), ('4', 'C'), ('3', 'D'), ('2', 'E'), ('0', 'F')))], max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player2score',
            field=models.CharField(choices=[('Round 1', (('5', 'A'), ('4', 'B'), ('3', 'C'), ('2', 'D'), ('1', 'E'), ('0', 'F'))), ('Round 2', (('6', 'A'), ('5', 'B'), ('4', 'C'), ('3', 'D'), ('2', 'E'), ('0', 'F')))], max_length=1, verbose_name='Category'),
        ),
    ]
