# Generated by Django 3.1.3 on 2020-12-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20201218_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='round_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.round'),
            preserve_default=False,
        ),
    ]
