# Generated by Django 3.1.3 on 2020-12-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20201218_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='team_name',
        ),
        migrations.AddField(
            model_name='score',
            name='team_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team'),
            preserve_default=False,
        ),
    ]
