# Generated by Django 3.1.3 on 2020-12-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_auto_20201218_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='score',
            old_name='player1score',
            new_name='playerscore',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player2score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.AddField(
            model_name='score',
            name='player_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.player'),
            preserve_default=False,
        ),
    ]
