# Generated by Django 3.1.3 on 2020-12-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_auto_20201219_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.team'),
            preserve_default=False,
        ),
    ]
